#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("DaysUntilXmasAndroid.Resource", IsApplication=true)]

namespace DaysUntilXmasAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.centered = global::DaysUntilXmasAndroid.Resource.Attribute.centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.clipPadding = global::DaysUntilXmasAndroid.Resource.Attribute.clipPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerColor = global::DaysUntilXmasAndroid.Resource.Attribute.footerColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerIndicatorHeight = global::DaysUntilXmasAndroid.Resource.Attribute.footerIndicatorHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerIndicatorStyle = global::DaysUntilXmasAndroid.Resource.Attribute.footerIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerIndicatorUnderlinePadding = global::DaysUntilXmasAndroid.Resource.Attribute.footerIndicatorUnderlinePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerLineHeight = global::DaysUntilXmasAndroid.Resource.Attribute.footerLineHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.footerPadding = global::DaysUntilXmasAndroid.Resource.Attribute.footerPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.linePosition = global::DaysUntilXmasAndroid.Resource.Attribute.linePosition;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.selectedBold = global::DaysUntilXmasAndroid.Resource.Attribute.selectedBold;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.selectedColor = global::DaysUntilXmasAndroid.Resource.Attribute.selectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.strokeWidth = global::DaysUntilXmasAndroid.Resource.Attribute.strokeWidth;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.titlePadding = global::DaysUntilXmasAndroid.Resource.Attribute.titlePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.topPadding = global::DaysUntilXmasAndroid.Resource.Attribute.topPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.unselectedColor = global::DaysUntilXmasAndroid.Resource.Attribute.unselectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiCirclePageIndicatorStyle = global::DaysUntilXmasAndroid.Resource.Attribute.vpiCirclePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiIconPageIndicatorStyle = global::DaysUntilXmasAndroid.Resource.Attribute.vpiIconPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiLinePageIndicatorStyle = global::DaysUntilXmasAndroid.Resource.Attribute.vpiLinePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiTabPageIndicatorStyle = global::DaysUntilXmasAndroid.Resource.Attribute.vpiTabPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiTitlePageIndicatorStyle = global::DaysUntilXmasAndroid.Resource.Attribute.vpiTitlePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Attribute.vpiUnderlinePageIndicatorStyle = global::DaysUntilXmasAndroid.Resource.Attribute.vpiUnderlinePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_circle_indicator_centered = global::DaysUntilXmasAndroid.Resource.Boolean.default_circle_indicator_centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_circle_indicator_snap = global::DaysUntilXmasAndroid.Resource.Boolean.default_circle_indicator_snap;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_line_indicator_centered = global::DaysUntilXmasAndroid.Resource.Boolean.default_line_indicator_centered;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_title_indicator_selected_bold = global::DaysUntilXmasAndroid.Resource.Boolean.default_title_indicator_selected_bold;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Boolean.default_underline_indicator_fades = global::DaysUntilXmasAndroid.Resource.Boolean.default_underline_indicator_fades;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_circle_indicator_fill_color = global::DaysUntilXmasAndroid.Resource.Color.default_circle_indicator_fill_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_circle_indicator_page_color = global::DaysUntilXmasAndroid.Resource.Color.default_circle_indicator_page_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_circle_indicator_stroke_color = global::DaysUntilXmasAndroid.Resource.Color.default_circle_indicator_stroke_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_line_indicator_selected_color = global::DaysUntilXmasAndroid.Resource.Color.default_line_indicator_selected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_line_indicator_unselected_color = global::DaysUntilXmasAndroid.Resource.Color.default_line_indicator_unselected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_title_indicator_footer_color = global::DaysUntilXmasAndroid.Resource.Color.default_title_indicator_footer_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_title_indicator_selected_color = global::DaysUntilXmasAndroid.Resource.Color.default_title_indicator_selected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_title_indicator_text_color = global::DaysUntilXmasAndroid.Resource.Color.default_title_indicator_text_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.default_underline_indicator_selected_color = global::DaysUntilXmasAndroid.Resource.Color.default_underline_indicator_selected_color;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__background_holo_dark = global::DaysUntilXmasAndroid.Resource.Color.vpi__background_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__background_holo_light = global::DaysUntilXmasAndroid.Resource.Color.vpi__background_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_disabled_holo_dark = global::DaysUntilXmasAndroid.Resource.Color.vpi__bright_foreground_disabled_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_disabled_holo_light = global::DaysUntilXmasAndroid.Resource.Color.vpi__bright_foreground_disabled_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_holo_dark = global::DaysUntilXmasAndroid.Resource.Color.vpi__bright_foreground_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_holo_light = global::DaysUntilXmasAndroid.Resource.Color.vpi__bright_foreground_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_inverse_holo_dark = global::DaysUntilXmasAndroid.Resource.Color.vpi__bright_foreground_inverse_holo_dark;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__bright_foreground_inverse_holo_light = global::DaysUntilXmasAndroid.Resource.Color.vpi__bright_foreground_inverse_holo_light;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__dark_theme = global::DaysUntilXmasAndroid.Resource.Color.vpi__dark_theme;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Color.vpi__light_theme = global::DaysUntilXmasAndroid.Resource.Color.vpi__light_theme;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_circle_indicator_radius = global::DaysUntilXmasAndroid.Resource.Dimension.default_circle_indicator_radius;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_circle_indicator_stroke_width = global::DaysUntilXmasAndroid.Resource.Dimension.default_circle_indicator_stroke_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_line_indicator_gap_width = global::DaysUntilXmasAndroid.Resource.Dimension.default_line_indicator_gap_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_line_indicator_line_width = global::DaysUntilXmasAndroid.Resource.Dimension.default_line_indicator_line_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_line_indicator_stroke_width = global::DaysUntilXmasAndroid.Resource.Dimension.default_line_indicator_stroke_width;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_clip_padding = global::DaysUntilXmasAndroid.Resource.Dimension.default_title_indicator_clip_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_indicator_height = global::DaysUntilXmasAndroid.Resource.Dimension.default_title_indicator_footer_indicator_height;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding = global::DaysUntilXmasAndroid.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_line_height = global::DaysUntilXmasAndroid.Resource.Dimension.default_title_indicator_footer_line_height;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_footer_padding = global::DaysUntilXmasAndroid.Resource.Dimension.default_title_indicator_footer_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_text_size = global::DaysUntilXmasAndroid.Resource.Dimension.default_title_indicator_text_size;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_title_padding = global::DaysUntilXmasAndroid.Resource.Dimension.default_title_indicator_title_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Dimension.default_title_indicator_top_padding = global::DaysUntilXmasAndroid.Resource.Dimension.default_title_indicator_top_padding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.bottom = global::DaysUntilXmasAndroid.Resource.Id.bottom;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.none = global::DaysUntilXmasAndroid.Resource.Id.none;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.top = global::DaysUntilXmasAndroid.Resource.Id.top;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.triangle = global::DaysUntilXmasAndroid.Resource.Id.triangle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Id.underline = global::DaysUntilXmasAndroid.Resource.Id.underline;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_circle_indicator_orientation = global::DaysUntilXmasAndroid.Resource.Integer.default_circle_indicator_orientation;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_title_indicator_footer_indicator_style = global::DaysUntilXmasAndroid.Resource.Integer.default_title_indicator_footer_indicator_style;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_title_indicator_line_position = global::DaysUntilXmasAndroid.Resource.Integer.default_title_indicator_line_position;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_underline_indicator_fade_delay = global::DaysUntilXmasAndroid.Resource.Integer.default_underline_indicator_fade_delay;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Integer.default_underline_indicator_fade_length = global::DaysUntilXmasAndroid.Resource.Integer.default_underline_indicator_fade_length;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.TextAppearance_TabPageIndicator = global::DaysUntilXmasAndroid.Resource.Style.TextAppearance_TabPageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Widget = global::DaysUntilXmasAndroid.Resource.Style.Widget;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Style.Widget_IconPageIndicator = global::DaysUntilXmasAndroid.Resource.Style.Widget_IconPageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator = global::DaysUntilXmasAndroid.Resource.Styleable.TitlePageIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_background = global::DaysUntilXmasAndroid.Resource.Styleable.TitlePageIndicator_android_background;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_textColor = global::DaysUntilXmasAndroid.Resource.Styleable.TitlePageIndicator_android_textColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_android_textSize = global::DaysUntilXmasAndroid.Resource.Styleable.TitlePageIndicator_android_textSize;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_clipPadding = global::DaysUntilXmasAndroid.Resource.Styleable.TitlePageIndicator_clipPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerColor = global::DaysUntilXmasAndroid.Resource.Styleable.TitlePageIndicator_footerColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight = global::DaysUntilXmasAndroid.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle = global::DaysUntilXmasAndroid.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding = global::DaysUntilXmasAndroid.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerLineHeight = global::DaysUntilXmasAndroid.Resource.Styleable.TitlePageIndicator_footerLineHeight;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_footerPadding = global::DaysUntilXmasAndroid.Resource.Styleable.TitlePageIndicator_footerPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_linePosition = global::DaysUntilXmasAndroid.Resource.Styleable.TitlePageIndicator_linePosition;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_selectedBold = global::DaysUntilXmasAndroid.Resource.Styleable.TitlePageIndicator_selectedBold;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_selectedColor = global::DaysUntilXmasAndroid.Resource.Styleable.TitlePageIndicator_selectedColor;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_titlePadding = global::DaysUntilXmasAndroid.Resource.Styleable.TitlePageIndicator_titlePadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.TitlePageIndicator_topPadding = global::DaysUntilXmasAndroid.Resource.Styleable.TitlePageIndicator_topPadding;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator = global::DaysUntilXmasAndroid.Resource.Styleable.ViewPagerIndicator;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle = global::DaysUntilXmasAndroid.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiIconPageIndicatorStyle = global::DaysUntilXmasAndroid.Resource.Styleable.ViewPagerIndicator_vpiIconPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiLinePageIndicatorStyle = global::DaysUntilXmasAndroid.Resource.Styleable.ViewPagerIndicator_vpiLinePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle = global::DaysUntilXmasAndroid.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle = global::DaysUntilXmasAndroid.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle;
			global::DK.Ostebaronen.Droid.ViewPagerIndicator.Resource.Styleable.ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = global::DaysUntilXmasAndroid.Resource.Styleable.ViewPagerIndicator_vpiUnderlinePageIndicatorStyle;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int centered = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int clipPadding = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int footerColor = 2130771979;
			
			// aapt resource value: 0x7f01000e
			public const int footerIndicatorHeight = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public const int footerIndicatorStyle = 2130771981;
			
			// aapt resource value: 0x7f01000f
			public const int footerIndicatorUnderlinePadding = 2130771983;
			
			// aapt resource value: 0x7f01000c
			public const int footerLineHeight = 2130771980;
			
			// aapt resource value: 0x7f010010
			public const int footerPadding = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int linePosition = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int selectedBold = 2130771986;
			
			// aapt resource value: 0x7f010007
			public const int selectedColor = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int strokeWidth = 2130771976;
			
			// aapt resource value: 0x7f010013
			public const int titlePadding = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int topPadding = 2130771988;
			
			// aapt resource value: 0x7f010009
			public const int unselectedColor = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int vpiCirclePageIndicatorStyle = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int vpiIconPageIndicatorStyle = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int vpiLinePageIndicatorStyle = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int vpiTabPageIndicatorStyle = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int vpiTitlePageIndicatorStyle = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int vpiUnderlinePageIndicatorStyle = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f070000
			public const int default_circle_indicator_centered = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int default_circle_indicator_snap = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int default_line_indicator_centered = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int default_title_indicator_selected_bold = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int default_underline_indicator_fades = 2131165188;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060008
			public const int default_circle_indicator_fill_color = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int default_circle_indicator_page_color = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int default_circle_indicator_stroke_color = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int default_line_indicator_selected_color = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int default_line_indicator_unselected_color = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int default_title_indicator_footer_color = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int default_title_indicator_selected_color = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int default_title_indicator_text_color = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int default_underline_indicator_selected_color = 2131099664;
			
			// aapt resource value: 0x7f060000
			public const int vpi__background_holo_dark = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int vpi__background_holo_light = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int vpi__bright_foreground_disabled_holo_dark = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int vpi__bright_foreground_disabled_holo_light = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int vpi__bright_foreground_holo_dark = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int vpi__bright_foreground_holo_light = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int vpi__bright_foreground_inverse_holo_dark = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int vpi__bright_foreground_inverse_holo_light = 2131099655;
			
			// aapt resource value: 0x7f060011
			public const int vpi__dark_theme = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int vpi__light_theme = 2131099666;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public const int default_circle_indicator_radius = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int default_circle_indicator_stroke_width = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int default_line_indicator_gap_width = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int default_line_indicator_line_width = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int default_line_indicator_stroke_width = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int default_title_indicator_clip_padding = 2131296261;
			
			// aapt resource value: 0x7f090007
			public const int default_title_indicator_footer_indicator_height = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int default_title_indicator_footer_indicator_underline_padding = 2131296264;
			
			// aapt resource value: 0x7f090006
			public const int default_title_indicator_footer_line_height = 2131296262;
			
			// aapt resource value: 0x7f090009
			public const int default_title_indicator_footer_padding = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int default_title_indicator_text_size = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int default_title_indicator_title_padding = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int default_title_indicator_top_padding = 2131296268;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_music = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_share = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int snow_1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int snow_2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int snow_3 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int snow_4 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int snow_flake = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int snowbackground = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0d0003
			public const int bottom = 2131558403;
			
			// aapt resource value: 0x7f0d0007
			public const int indicator = 2131558407;
			
			// aapt resource value: 0x7f0d000b
			public const int menu_about = 2131558411;
			
			// aapt resource value: 0x7f0d000a
			public const int menu_music = 2131558410;
			
			// aapt resource value: 0x7f0d0009
			public const int menu_share = 2131558409;
			
			// aapt resource value: 0x7f0d0000
			public const int none = 2131558400;
			
			// aapt resource value: 0x7f0d0008
			public const int pager = 2131558408;
			
			// aapt resource value: 0x7f0d0006
			public const int titleDays = 2131558406;
			
			// aapt resource value: 0x7f0d0005
			public const int titleText = 2131558405;
			
			// aapt resource value: 0x7f0d0004
			public const int top = 2131558404;
			
			// aapt resource value: 0x7f0d0001
			public const int triangle = 2131558401;
			
			// aapt resource value: 0x7f0d0002
			public const int underline = 2131558402;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int default_circle_indicator_orientation = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int default_title_indicator_footer_indicator_style = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int default_title_indicator_line_position = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int default_underline_indicator_fade_delay = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int default_underline_indicator_fade_length = 2131230724;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FragmentScreenSlidePage = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0c0000
			public const int menu_main = 2131492864;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int Bethlehem = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Deck_The_Halls = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Jingle_Bells = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int Oh_Xmas = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int We_Wish_You = 2131034116;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0b0000
			public const int app_name = 2131427328;
			
			// aapt resource value: 0x7f0b0004
			public const int days_until = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int lorem_ipsum = 2131427333;
			
			// aapt resource value: 0x7f0b0002
			public const int menu_about = 2131427330;
			
			// aapt resource value: 0x7f0b0001
			public const int menu_music = 2131427329;
			
			// aapt resource value: 0x7f0b0003
			public const int menu_share = 2131427331;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0004
			public const int MyActionBar = 2131361796;
			
			// aapt resource value: 0x7f0a0001
			public const int TextAppearance_TabPageIndicator = 2131361793;
			
			// aapt resource value: 0x7f0a0003
			public const int TransparentTheme = 2131361795;
			
			// aapt resource value: 0x7f0a0000
			public const int Widget = 2131361792;
			
			// aapt resource value: 0x7f0a0002
			public const int Widget_IconPageIndicator = 2131361794;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int wearable_app_desc = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] TitlePageIndicator = new int[]
			{
					16842901,
					16842904,
					16842964,
					2130771975,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: 2
			public const int TitlePageIndicator_android_background = 2;
			
			// aapt resource value: 1
			public const int TitlePageIndicator_android_textColor = 1;
			
			// aapt resource value: 0
			public const int TitlePageIndicator_android_textSize = 0;
			
			// aapt resource value: 4
			public const int TitlePageIndicator_clipPadding = 4;
			
			// aapt resource value: 5
			public const int TitlePageIndicator_footerColor = 5;
			
			// aapt resource value: 8
			public const int TitlePageIndicator_footerIndicatorHeight = 8;
			
			// aapt resource value: 7
			public const int TitlePageIndicator_footerIndicatorStyle = 7;
			
			// aapt resource value: 9
			public const int TitlePageIndicator_footerIndicatorUnderlinePadding = 9;
			
			// aapt resource value: 6
			public const int TitlePageIndicator_footerLineHeight = 6;
			
			// aapt resource value: 10
			public const int TitlePageIndicator_footerPadding = 10;
			
			// aapt resource value: 11
			public const int TitlePageIndicator_linePosition = 11;
			
			// aapt resource value: 12
			public const int TitlePageIndicator_selectedBold = 12;
			
			// aapt resource value: 3
			public const int TitlePageIndicator_selectedColor = 3;
			
			// aapt resource value: 13
			public const int TitlePageIndicator_titlePadding = 13;
			
			// aapt resource value: 14
			public const int TitlePageIndicator_topPadding = 14;
			
			public static int[] ViewPagerIndicator = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			// aapt resource value: 1
			public const int ViewPagerIndicator_vpiIconPageIndicatorStyle = 1;
			
			// aapt resource value: 2
			public const int ViewPagerIndicator_vpiLinePageIndicatorStyle = 2;
			
			// aapt resource value: 4
			public const int ViewPagerIndicator_vpiTabPageIndicatorStyle = 4;
			
			// aapt resource value: 3
			public const int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 3;
			
			// aapt resource value: 5
			public const int ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
